/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TicketsController_list"];
        put?: never;
        post: operations["TicketsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets/sort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TicketsController_sort"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TicketsController_get"];
        put?: never;
        post?: never;
        delete: operations["TicketsController_remove"];
        options?: never;
        head?: never;
        patch: operations["TicketsController_update"];
        trace?: never;
    };
    "/v1/tickets/{ticketId}/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["TicketsController_move"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTicketDto: {
            /** @description 앞뒤 공백은 제거된다. */
            title: string;
            description?: string | null;
            /**
             * @default MEDIUM
             * @enum {string}
             */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** Format: date-time */
            dueAt?: string | null;
            /** @description 앞뒤 공백 제거·소문자로 정규화, 중복 제거. 최대 10개, 이름 최대 30자. */
            tags?: string[];
        };
        TicketResponse: {
            /** Format: uuid */
            ticketId: string;
            title: string;
            description: string | null;
            /** @enum {string} */
            status: "TODO" | "IN_PROGRESS" | "DONE";
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** Format: date-time */
            dueAt: string | null;
            /** @description 이름 오름차순. */
            tags: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SortColumnDto: {
            /** @enum {string} */
            status: "TODO" | "IN_PROGRESS" | "DONE";
            /** @enum {string} */
            sortBy: "PRIORITY" | "DUE_AT";
            /** @enum {string} */
            direction: "ASC" | "DESC";
        };
        UpdateTicketDto: {
            /** @description 앞뒤 공백은 제거된다. */
            title?: string;
            /** @description null·빈 문자열·공백뿐이면 설명이 지워진다. */
            description?: string | null;
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /**
             * Format: date-time
             * @description null이면 마감일이 지워진다.
             */
            dueAt?: string | null;
            /** @description 앞뒤 공백 제거·소문자로 정규화, 중복 제거. 최대 10개, 이름 최대 30자. */
            tags?: string[];
        };
        MovePositionDto: {
            /**
             * @description 이동할 대상 컬럼.
             * @enum {string}
             */
            status: "TODO" | "IN_PROGRESS" | "DONE";
            /**
             * Format: uuid
             * @description 기준 카드. 대상 컬럼에 다른 카드가 없으면 생략한다.
             */
            anchorTicketId?: string;
            /**
             * @description 기준 카드의 앞 또는 뒤.
             * @enum {string}
             */
            placement: "BEFORE" | "AFTER";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TicketsController_list: {
        parameters: {
            query?: {
                /** @description 제목·설명 부분 일치(대소문자 무시). */
                q?: string;
                status?: ("TODO" | "IN_PROGRESS" | "DONE")[];
                priority?: ("LOW" | "MEDIUM" | "HIGH" | "URGENT")[];
                /** @description 하나라도 가진 티켓(OR). 이름은 정규화해 비교한다. */
                tag?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"][];
                };
            };
        };
    };
    TicketsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
        };
    };
    TicketsController_sort: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SortColumnDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TicketsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
        };
    };
    TicketsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TicketsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
        };
    };
    TicketsController_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovePositionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
        };
    };
}
